# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      - name: download and run mergebase
        run: |
          wget --header="X-Authorization:${{ secrets.MB_DEMO_TOKEN }}" https://demo.mergebase.com/api/update/clt/mergebase.jar
          java -jar mergebase.jar --name=${{github.repository}}@${{github.ref}} --exitZero .
      - name: MergeBase
        # You may pin to the exact commit or the version.
        # uses: mergebase/mergebase-scan-action@8d5b99f95920de6d460f72944ce3e3d9202bec59
        uses: mergebase/mergebase-scan-action@1.0.0
        with:
        # name of your MB project
          project_name: action_test
         # Customer token from your MB dashboard
          mb_token: ${{ secrets.MB_DEMO_TOKEN }}
        # Your dashboard URL in the form https://[domain].mergebase.com
          mb_url: https://demo.mergebase.com
        # additional command line arguments. See CLT user guide for list of available options
          additional_args: --exitZero
          
  
